import "./globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import { AppLoaderScreen } from "@/domains/shared/components/app-loader-screen";
import { AuthenticationProvider } from "@/domains/auth/providers/auth-provider";
import { MemberContainer } from "@/domains/member/container/member-container";
import { Member } from "@prisma/client";
// import { SocketProvider } from "@/domains/communication-channels/providers/socket-provider";
// import { ThemeProvider } from "@/components/providers/theme-provider";
// // import { cn } from "@/lib/utils";
// import { ModalProvider } from "@/components/providers/modal-provider";
// import { SocketProvider } from "@/components/providers/socket-provider";
// import { QueryProvider } from "@/components/providers/query-provider";
// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const font = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Top Trump",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={font.className}>
          {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={false}
            storageKey="top-trump"
          >
       
              <ModalProvider />
              <QueryProvider>
                <>
                  <ReactQueryDevtools initialIsOpen={false} /> */}
          <ClerkLoading>
            <AppLoaderScreen />
          </ClerkLoading>
          <ClerkLoaded>
            <MemberContainer>
              {(member: Member) => (
                <AuthenticationProvider member={member}>
                  {children}
                </AuthenticationProvider>
              )}
            </MemberContainer>
          </ClerkLoaded>
          {/* </>
              </QueryProvider>
            </SocketProvider>
          </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
